// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using infrastructure;

namespace infrastructure.Migrations
{
    [DbContext(typeof(DbContext))]
    [Migration("20200912152502_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("infrastructure.records.BillRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("infrastructure.records.BusinessRuleRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("DelayedDaysEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DelayedDaysStart")
                        .HasColumnType("INTEGER");

                    b.Property<double>("InterestPerDay")
                        .HasColumnType("REAL");

                    b.Property<double>("Penalty")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("BusinessRules");
                });
#pragma warning restore 612, 618
        }
    }
}
